services:
  db:
    image: postgres:15
    container_name: postgres_prueba_tecnica
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: prueba_tecnica
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_prueba_tecnica
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@prueba.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network
    depends_on:
      - db

networks:
  pg-network:
